### PR TITLE
Add python 3 support

### PR DESCRIPTION
**Pull request by charliewolf**

### CODE REVIEW

**Comment by iurisilvio** [comment]
Thanks! I want to support py3. Possibly related to #6.

I added py3 to travis build and it passed.

Can you provide a small example or write a test to this issue?

Maybe your issue was fixed with 675c6a49f9dbd6cf4d47b9e717d2ee32c718ec64. I released a new version (0.1.3) with this change today.

**Comment by charliewolf** [comment]
@iurisilvio The tests already fail on python 3.5 for me.

**Comment by charliewolf** [comment]
```
======================================================================
ERROR: test_cache_hit (flask_sqlalchemy_cache.tests.test_minimal.TestFromCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/crw/Flask-SQLAlchemy-Cache/flask_sqlalchemy_cache/tests/test_minimal.py", line 54, in test_cache_hit
    country = caching_q.first()
  File "/home/crw/howl-python/venv3/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/home/crw/howl-python/venv3/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/home/crw/Flask-SQLAlchemy-Cache/flask_sqlalchemy_cache/core.py", line 48, in __iter__
    return iter(self.get_value(createfunc=func))
  File "/home/crw/Flask-SQLAlchemy-Cache/flask_sqlalchemy_cache/core.py", line 67, in get_value
    cache, cache_key = self._get_cache_plus_key()
  File "/home/crw/Flask-SQLAlchemy-Cache/flask_sqlalchemy_cache/core.py", line 54, in _get_cache_plus_key
    key = getattr(self, '_cache_key', self.key_from_query())
  File "/home/crw/Flask-SQLAlchemy-Cache/flask_sqlalchemy_cache/core.py", line 116, in key_from_query
    return md5(key).hexdigest()
TypeError: Unicode-objects must be encoded before hashing

```

**Comment by iurisilvio** [comment]
Great! I don't know why tests passed with tox. I was doing something wrong.

I fixed travis build and now I reproduced your issue. Merged!

**Pull request merged**
